SET FOREIGN_KEY_CHECKS=0;
/* Drop Tables */
DROP TABLE IF EXISTS T_USERS CASCADE;

DROP TABLE IF EXISTS T_ORDERS CASCADE;

DROP TABLE IF EXISTS T_PAYMENTS CASCADE;

DROP TABLE IF EXISTS T_CARS CASCADE;

DROP TABLE IF EXISTS T_CARS_TYPE CASCADE;

DROP TABLE IF EXISTS T_CARS_MODEL CASCADE;

DROP TABLE IF EXISTS T_CARS_BRAND CASCADE;

/* Create Tables */
CREATE TABLE T_USERS (
	U_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	U_USERNAME VARCHAR(100) NOT NULL,
    U_USEREMAIL VARCHAR(100) NOT NULL,
    U_PAYMENT_CARD VARCHAR(16) NOT NULL,
	CONSTRAINT T_USERS_PK PRIMARY KEY (U_ID ASC)
);

CREATE TABLE T_ORDERS (
	O_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	O_PRICE FLOAT NOT NULL,
    O_DATETIME DATETIME NOT NULL,
    O_USER_ID BIGINT UNSIGNED NOT NULL,
    O_CAR_ID BIGINT UNSIGNED NOT NULL,
    O_PAYMENT_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT T_ORDERS_PK PRIMARY KEY (O_ID ASC)
);

CREATE TABLE T_CARS (
	C_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	C_NUMBER VARCHAR(30) NOT NULL,
    C_BRAND_ID BIGINT UNSIGNED NOT NULL,
	C_MODEL_ID BIGINT UNSIGNED NOT NULL,
    C_TYPE_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT T_CARS_PK PRIMARY KEY (C_ID ASC)
);

CREATE TABLE T_CARS_TYPE (
	CT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CT_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT T_CARS_TYPE_PK PRIMARY KEY (CT_ID ASC)
);

CREATE TABLE T_CARS_MODEL (
	CM_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CM_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT T_CARS_MODEL PRIMARY KEY (CM_ID ASC)
);

CREATE TABLE T_CARS_BRAND (
	CB_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CB_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT T_CARS_BRAND PRIMARY KEY (CB_ID ASC)
);

CREATE TABLE T_PAYMENTS (
	P_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	P_DATETIME DATETIME NOT NULL,
	CONSTRAINT T_PAYMENTS_PK PRIMARY KEY (P_ID ASC)
);

ALTER TABLE T_ORDERS ADD CONSTRAINT T_ORDERS_FK_USERS FOREIGN KEY (O_USER_ID) 
REFERENCES T_USERS (U_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_ORDERS ADD CONSTRAINT T_ORDERS_FK_CARS FOREIGN KEY (O_CAR_ID) 
REFERENCES T_CARS (C_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_ORDERS ADD CONSTRAINT T_ORDERS_FK_PAYMENTS FOREIGN KEY (O_PAYMENT_ID) 
REFERENCES T_PAYMENTS (P_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT T_CARS_FK_CARTYPE FOREIGN KEY (C_TYPE_ID) 
REFERENCES T_CARS_TYPE (CT_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT T_CARS_FK_CARBRAND FOREIGN KEY (C_BRAND_ID) 
REFERENCES T_CARS_BRAND (CB_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT T_CARS_FK_CARMODEL FOREIGN KEY (C_MODEL_ID) 
REFERENCES T_CARS_MODEL (CM_ID) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;