SET FOREIGN_KEY_CHECKS=0;
/* Drop Tables */
DROP TABLE IF EXISTS T_USERS CASCADE;

DROP TABLE IF EXISTS T_ORDERS CASCADE;

DROP TABLE IF EXISTS T_PAYMENTS CASCADE;

DROP TABLE IF EXISTS T_CARS CASCADE;

DROP TABLE IF EXISTS T_CARS_TYPE CASCADE;

DROP TABLE IF EXISTS T_CARS_MODEL CASCADE;

DROP TABLE IF EXISTS T_CARS_BRAND CASCADE;

DROP TABLE IF EXISTS T_ROLES CASCADE;

DROP TABLE IF EXISTS T_M2M_USERS_ROLES CASCADE;

DROP TABLE IF EXISTS T_PERMISSIONS CASCADE;

DROP TABLE IF EXISTS T_M2M_USERS_ORDERS CASCADE;

DROP TABLE IF EXISTS T_M2M_ORDERS_PAYMENTS CASCADE;

/* Create Tables */
CREATE TABLE T_USERS (
	U_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	U_USERNAME VARCHAR(100) NOT NULL,
    U_USEREMAIL VARCHAR(100) NOT NULL,
    U_PAYMENT_CARD VARCHAR(16) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (U_ID ASC)
);

CREATE TABLE T_ORDERS (
	O_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	O_PRICE FLOAT NOT NULL,
    O_DATETIME DATETIME NOT NULL,
    O_CAR_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT PK_ORDERS PRIMARY KEY (O_ID ASC)
);

CREATE TABLE T_CARS (
	C_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	C_NUMBER VARCHAR(30) NOT NULL,
    C_BRAND_ID BIGINT UNSIGNED NOT NULL,
	C_MODEL_ID BIGINT UNSIGNED NOT NULL,
    C_TYPE_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT PK_CARS PRIMARY KEY (C_ID ASC)
);

CREATE TABLE T_CARS_TYPE (
	CT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CT_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CARS_TYPE PRIMARY KEY (CT_ID ASC)
);

CREATE TABLE T_CARS_MODEL (
	CM_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CM_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARS_MODEL PRIMARY KEY (CM_ID ASC)
);

CREATE TABLE T_CARS_BRAND (
	CB_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CB_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARS_BRAND PRIMARY KEY (CB_ID ASC)
);

CREATE TABLE T_PAYMENTS (
	P_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	P_DATETIME DATETIME NOT NULL,
	CONSTRAINT PK_PAYMENTS PRIMARY KEY (P_ID ASC)
);

CREATE TABLE T_ROLES (
	R_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    R_NAME VARCHAR(100) NOT NULL,
    R_DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (R_ID ASC)
);

CREATE TABLE T_M2M_USERS_ROLES (
	U_ID BIGINT UNSIGNED NOT NULL,
    R_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT PK_M2M_USERS_ROLES PRIMARY KEY (U_ID ASC, R_ID ASC)
);

CREATE TABLE T_PERMISSIONS (
	PRMS_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRMS_NAME VARCHAR(100) NOT NULL,
    PRMS_R_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT PK_PERMISSIONS PRIMARY KEY (PRMS_ID ASC)
);

CREATE TABLE T_M2M_USERS_ORDERS (
	U_ID BIGINT UNSIGNED NOT NULL,
    O_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT PK_M2M_USERS_ORDERS PRIMARY KEY (U_ID ASC, O_ID ASC)
);

CREATE TABLE T_M2M_ORDERS_PAYMENTS (
	O_ID BIGINT UNSIGNED NOT NULL,
    P_ID BIGINT UNSIGNED NOT NULL,
    CONSTRAINT PK_M2M_ORDERS_PAYMENTS PRIMARY KEY (O_ID ASC, P_ID ASC)
);

ALTER TABLE T_ORDERS ADD CONSTRAINT FK_ORDERS_CARS FOREIGN KEY (O_CAR_ID) 
REFERENCES T_CARS (C_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT FK_CARS_CARTYPE FOREIGN KEY (C_TYPE_ID) 
REFERENCES T_CARS_TYPE (CT_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT FK_CARS_CARBRAND FOREIGN KEY (C_BRAND_ID) 
REFERENCES T_CARS_BRAND (CB_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_CARS ADD CONSTRAINT FK_CARS_CARMODEL FOREIGN KEY (C_MODEL_ID) 
REFERENCES T_CARS_MODEL (CM_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_USERS_ROLES ADD CONSTRAINT FK_USERS_ROLES_ROLES FOREIGN KEY (R_ID)
REFERENCES T_ROLES (R_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_USERS_ROLES ADD CONSTRAINT FK_USERS_ROLES_USERS FOREIGN KEY (U_ID)
REFERENCES T_USERS (U_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS_ROLES FOREIGN KEY (PRMS_R_ID)
REFERENCES T_ROLES (R_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_USERS_ORDERS ADD CONSTRAINT FK_M2M_USERS_ORDERS_ORDERS FOREIGN KEY (O_ID)
REFERENCES T_ORDERS (O_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_USERS_ORDERS ADD CONSTRAINT FK_M2M_USERS_ORDERS_USERS FOREIGN KEY (U_ID)
REFERENCES T_USERS (U_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_ORDERS_PAYMENTS ADD CONSTRAINT FK_M2M_ORDERS_PAYMENTS_PAYMENTS FOREIGN KEY (P_ID)
REFERENCES T_PAYMENTS (P_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE T_M2M_ORDERS_PAYMENTS ADD CONSTRAINT FK_M2M_ORDERS_PAYMENTS_ORDERS FOREIGN KEY (O_ID)
REFERENCES T_ORDERS (O_ID) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;